### PR TITLE
#49376 Check if sdX schedulers are set to deadline

### PR DESCRIPTION
**Pull request by BarbUk**

### CODE REVIEW

**Comment by cyril-bouthors** [comment]
Looks good except a few little things:

 - check if the file exist before using it in the for loop, ```$file``` is defined as ```/sys/block/sd?/queue/scheduler``` in that case because it's not expanded and the grep will fail. Do something like: ```[ ! -f $file ] && continue```
 - check other block device names like ```/dev/vd?``` and maybe others. Check with ```dsh``` to see what's missing
 - typo "All [...] scheduler are" (missing the s)

**Comment by BarbUk** [comment]
For the second point, I originally wanted to detect the partitions with /proc/partitions, but only sdX have a scheduler. The others /queue/scheduler are set to "none".


`cat /proc/partitions`
major minor  #blocks  name
   8        0  487849984 sda
   8        1     291840 sda1
   8        2    5242880 sda2
   8        3  482314240 sda3
 254        0   20971520 dm-0
 254        1     131072 dm-1
 147        0   20971520 drbd0


`tail -n +1 /sys/block/*/queue/scheduler`
==> /sys/block/dm-0/queue/scheduler <==
none
==> /sys/block/dm-1/queue/scheduler <==
none
==> /sys/block/drbd0/queue/scheduler <==
none
==> /sys/block/sda/queue/scheduler <==
noop [deadline] cfq

**Comment by cyril-bouthors** [comment]
Some virtual machines have ```/dev/vda``` devices with an I/O scheduler if I remember correctly.

Can you please check all devices with ```DSH```?

**Comment by cyril-bouthors** [comment]
Any update on that?

**Comment by BarbUk** [comment]
Yep, I now check for all scheduler in /sys/block/{sd?,vd?}/queue/scheduler.
Is this ok ?

**Pull request merged**
